name: condascipyheroku
dependencies:
- python=3.5.1
- pip=8.0.1
- numpy=1.10.1
- scipy=0.16.0
- flask=0.10.1
- itsdangerous=0.24
- jinja2=2.8
- markupsafe=0.23
- scikit-learn=0.17
- setuptools=19.4
- werkzeug=0.11.3
- wheel=0.26.0
- pip:
  - gunicorn==19.4.5

